export const GETONE_PRODUCT_ATTEMPT = "GETONE_PRODUCT_ATTEMPT";
export const GETONE_PRODUCT_SUCCESS = "GETONE_PRODUCT_SUCCESS";
export const GETONE_PRODUCT_FAILURE = "GETONE_PRODUCT_FAILURE";

export const GET_SUBCATEGORY_ATTEMPT = "GET_SUBCATEGORY_ATTEMPT";
export const GET_SUBCATEGORY_SUCCESS = "GET_SUBCATEGORY__SUCCESS";
export const GET_SUBCATEGORY_FAILURE = "GET_SUBCATEGORY__FAILURE";

export const GET_CATEGORY_ATTEMPT = "GET_CATEGORY_ATTEMPT";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY__SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY__FAILURE";

export const GET_BY_SEARCH_ATTEMPT = "GET_BY_SEARCH_ATTEMPT";
export const GET_BY_SEARCH_SUCCESS = "GET_BY_SEARCH__SUCCESS";
export const GET_BY_SEARCH_FAILURE = "GET_BY_SEARCH__FAILURE";

export const GET_BY_BRAND_ATTEMPT = "GET_BY_BRAND_ATTEMPT";
export const GET_BY_BRAND_SUCCESS = "GET_BY_BRAND__SUCCESS";
export const GET_BY_BRAND_FAILURE = "GET_BY_BRAND__FAILURE";
