const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const REG_ATTEMPT = "REG_ATTEMPT";
const REG_SUCCESS = "REG_SUCCESS";
const REG_FAILURE = "REG_FAILURE";

const LOGOUT = "LOGOUT";

export {
  LOGIN_ATTEMPT,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REG_ATTEMPT,
  REG_SUCCESS,
  REG_FAILURE,
  LOGOUT,
};
